//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMOElection.JMOServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JMOServiceReference.IJMOVoteService")]
    public interface IJMOVoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMOVoteService/AllowVote", ReplyAction="http://tempuri.org/IJMOVoteService/AllowVoteResponse")]
        bool AllowVote(int Booth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMOVoteService/AllowVote", ReplyAction="http://tempuri.org/IJMOVoteService/AllowVoteResponse")]
        System.Threading.Tasks.Task<bool> AllowVoteAsync(int Booth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMOVoteService/VoteFeedback", ReplyAction="http://tempuri.org/IJMOVoteService/VoteFeedbackResponse")]
        void VoteFeedback(int Booth, int TotalVotes, bool IsVotingOpen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJMOVoteService/VoteFeedback", ReplyAction="http://tempuri.org/IJMOVoteService/VoteFeedbackResponse")]
        System.Threading.Tasks.Task VoteFeedbackAsync(int Booth, int TotalVotes, bool IsVotingOpen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJMOVoteServiceChannel : JMOElection.JMOServiceReference.IJMOVoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JMOVoteServiceClient : System.ServiceModel.ClientBase<JMOElection.JMOServiceReference.IJMOVoteService>, JMOElection.JMOServiceReference.IJMOVoteService {
        
        public JMOVoteServiceClient() {
        }
        
        public JMOVoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JMOVoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JMOVoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JMOVoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AllowVote(int Booth) {
            return base.Channel.AllowVote(Booth);
        }
        
        public System.Threading.Tasks.Task<bool> AllowVoteAsync(int Booth) {
            return base.Channel.AllowVoteAsync(Booth);
        }
        
        public void VoteFeedback(int Booth, int TotalVotes, bool IsVotingOpen) {
            base.Channel.VoteFeedback(Booth, TotalVotes, IsVotingOpen);
        }
        
        public System.Threading.Tasks.Task VoteFeedbackAsync(int Booth, int TotalVotes, bool IsVotingOpen) {
            return base.Channel.VoteFeedbackAsync(Booth, TotalVotes, IsVotingOpen);
        }
    }
}
